apps/contabilidad/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import *
from .viewsHelpers import *

urlpatterns = [
    path('', panel, name='inicio'),
    path('crear-cuenta/', crear_cuenta, name='crear_cuenta'),
    path('crear-egreso/<int:cuenta_id>/', crear_egreso, name='crear_egreso'),
    path('crear-ingreso/<int:cuenta_id>/', crear_ingreso, name='crear_ingreso'),
    path('crear-transferencia/<int:cuenta_id>/', transferir, name='transferir'),

    path('crear-persona/', crear_persona, name='crear_persona'),
    path('persona/<int:persona_id>/', vista_persona, name='vista_persona'),
    path('administar-personas', listar_personas, name='listar_personas'),
    path('editar-persona/<int:pk>/', login_required(EditarPersona.as_view()), name = 'editar_persona'),
    path('eliminar-persona/<int:pk>/', login_required(EliminarPersona.as_view()), name = 'eliminar_persona'),
    path('ocultar-persona/<int:persona_id>/', ocultar_persona, name = 'ocultar_persona'),

    path('prestamos/', listar_prestamos, name='listar_prestamos'),
    path('prestamo/<int:prestamo_id>/', vista_prestamo, name='vista_prestamo'),
    path('crear-prestamo/<int:persona_id>/', crear_prestamo, name='crear_prestamo'),
    path('pagar-prestamo/<int:prestamo_id>/', pagar_prestamo, name='pagar_prestamo'),
    path('pagar-conjunto-prestamos/<int:persona_id>/', pagarConjuntoPrestamos, name='pagarConjuntoPrestamos'),
    path('eliminar-prestamo/<int:prestamo_id>/', eliminar_prestamo, name='eliminar_prestamo'),
    path('solicitudes-prestamos/', vistaSolicitudesPrestamos, name='vistaSolicitudesPrestamos'),
    path('solicitudPagoPrestamo/<int:id>/', vistaSolicitudPagoPrestamo, name='vistaSolicitudPagoPrestamo'),
    path('cambiarEstadoSolicitudPagoPrestamo/<int:id>/<int:nuevoEstado>/', cambiarEstadoSolicitudPagoPrestamo, name='cambiarEstadoSolicitudPagoPrestamo'),
    path('cambiarEstadoSolicitudCreacionPrestamo/<int:id>/<int:nuevoEstado>/', cambiarEstadoSolicitudCreacionPrestamo, name='cambiarEstadoSolicitudCreacionPrestamo'),
    path('eliminar-solicitudPagoPrestamo/<int:id>/', eliminarSolicitudPagoPrestamo, name='eliminarSolicitudPagoPrestamo'),

    path('crear-etiqueta/', crear_etiqueta, name='crear_etiqueta'),
    path('administar-etiquetas', listar_etiquetas, name='listar_etiquetas'),
    path('editar-etiqueta/<int:pk>/', login_required(EditarEtiqueta.as_view()), name = 'editar_etiqueta'),
    path('eliminar-etiqueta/<int:pk>/', login_required(EliminarEtiqueta.as_view()), name = 'eliminar_etiqueta'),

    path('movimientos/', todos_movimientos, name='todos_movimientos'),
    path('movimientos-cuenta/<int:cuenta_id>/', movimientos_cuenta, name='movimientos_cuenta'),
    path('movimientos-dia/<str:tipo>/<str:fecha>/', movimientos_dia, name='movimientos_dia'),
    path('movimientos-mes/<str:tipo>/<str:fecha>/', movimientos_mes, name='movimientos_mes'),
    path('movimientos-etiqueta/<int:etiqueta_id>/', movimientos_etiqueta, name='movimientos_etiqueta'),
    path('movimientos-etiqueta-mes/<str:etiqueta_id>/<str:tipo>/<str:periodo>/', movimientos_etiqueta_mes, name='movimientos_etiqueta_mes'),

    path('transaccion/<int:transaccion_id>/', vista_transaccion, name='vista_transaccion'),
    path('transaccion-rollback/<int:transaccion_id>/', transaccion_rollback, name='transaccion_rollback'),
    path('transacciones-programadas/', transacciones_programadas, name='transacciones_programadas'),
    path('crear-transaccion-programada/', crear_transaccion_programada, name='crear_transaccion_programada'),
    path('pagar-transaccion-programada/<int:transaccion_id>/', pagar_transaccion_programada, name='pagar_transaccion_programada'),

    path('relacionarUsuarioConTransaccion/', relacionarUsuarioConTransaccion, name='relacionarUsuarioConTransaccion'),

    path('crear-creditCard/', crear_creditCard, name='crear_creditCard'),
    path('creditCard/<int:creditCard_id>/', vista_creditCard, name='vista_creditCard'),
    path('listar-creditcards/', listar_creditCards, name='listar_creditCards'),
    path('crear-compra/<int:creditCard_id>/', crear_compra, name='crear_compra'),
    path('compra-detalles/<int:compra_id>/', vista_compra, name='vista_compra'),
    path('pagar-tarjeta/<int:tarjeta_id>/', pagar_tarjeta, name='pagar_tarjeta'),
    path('eliminar-compra/<int:compra_id>/', eliminar_compra, name='eliminar_compra'),
    
    path('agregar-subtag/<int:transaccion_id>/', agregar_subtag, name='agregar_subtag'),

    path('agregar-transaccion-grupo/<int:transaccionPadre_id>/', agregar_transaccion_grupo, name='agregar_transaccion_grupo'),
]

miscuentas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.contabilidad.urls', 'panel'))),
    path('user/', include(('apps.usuario.urls', 'user'))),
    path('reporte/', include(('apps.reporte.urls', 'reporte'))),
    path('pagos/', include(('apps.pagos.urls', 'pagos'))),
    path('shared/', include(('apps.publico.urls', 'publico'))),
    path('apto/', include(('apps.apto.urls', 'apto'))),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/contabilidad/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Cuenta(models.Model):
    nombre = models.CharField('Nombre de la Cuenta', max_length=30)
    saldo = models.IntegerField('Saldo de cuenta')
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    visible = models.BooleanField('Visible', default=True)

    class Meta:
        verbose_name = 'Cuenta'
        verbose_name_plural = 'Cuentas'
        ordering = ['nombre']

    def __str__(self):
        return "{} - {}".format(self.user.username, self.nombre)

class Etiqueta(models.Model):
    nombre = models.CharField('Nombre de la Etiqueta', max_length=50)
    tipo = models.IntegerField(default=1)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Etiquetas'
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

class SubTag(models.Model):
    nombre = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'SubTag'
        verbose_name_plural = 'SubTags'
        ordering = ['nombre']
    def __str__(self):
        return self.nombre

class Persona(models.Model):
    nombre = models.CharField('Nombre de la Persona', max_length=90)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    visible = models.BooleanField('Visible', default=True)

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

class Transaccion(models.Model):
    TIPO_CHOICES = [('ingreso', 'Ingreso'),
                    ('egreso', 'Egreso')]
    tipo = models.CharField('Tipo de transaccion', max_length=30, choices=TIPO_CHOICES)
    saldo_anterior = models.IntegerField('Saldo anterior')
    cantidad = models.IntegerField('Cantidad')
    info = models.TextField('Descripción', max_length=300)
    fecha = models.DateTimeField('Fecha')
    estado = models.IntegerField('Estado', default=1) # 0 programada, 1 realizada, 2 realizada agrupada, 3 padre grupo
    cuenta = models.ForeignKey(Cuenta, null=True, blank=True, on_delete=models.CASCADE)
    etiqueta = models.ForeignKey(Etiqueta, null=True, blank=True, on_delete=models.CASCADE)
    subtag = models.ForeignKey(SubTag, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Transaccion'
        verbose_name_plural = 'Transacciones'
        ordering = ['-fecha']

    def __str__(self):
        cuentaNombre = self.cuenta.nombre if self.cuenta else "(no Cuenta)"
        return "{} - {} {} ${} - {}".format(self.id, self.tipo, cuentaNombre, self.cantidad, self.fecha.strftime("%d/%b/%Y"))

class Prestamo(models.Model):
    TIPO_CHOICES = [('yopresto', 'Yo presto'),
                    ('meprestan','Me prestan')]
    tipo = models.CharField('Tipo de prestamo', max_length=30, choices=TIPO_CHOICES)
    cantidad = models.IntegerField('Cantidad')
    info = models.CharField('Informacion', max_length=200)
    cancelada = models.BooleanField('Cancelada', default=False)
    saldo_pendiente = models.IntegerField('Saldo pendiente')
    fecha = models.DateTimeField('Fecha')
    cuenta = models.ForeignKey(Cuenta, null=True, blank=True, on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, null=False, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Prestamo'
        verbose_name_plural = 'Prestamos'
        ordering = ['-fecha']

    def __str__(self):
        return "{} - {} {} - {}".format(self.id, self.tipo, self.persona.nombre, self.fecha.strftime("%d/%b/%Y"))

    def nombreTipoInvertido(self):
        tipo_dict = dict(self.TIPO_CHOICES)
        tipoContrario = 'yopresto' if self.tipo == 'meprestan' else 'meprestan'
        return tipo_dict.get(tipoContrario, None)


class TransaccionPrestamo(models.Model):
    transaccion = models.ForeignKey(Transaccion, null=False, blank=False, on_delete=models.CASCADE)
    prestamo = models.ForeignKey(Prestamo, null=False, blank=False, on_delete=models.CASCADE)
    tipo = models.IntegerField(default=2) # 1 ingreso/egreso prestamo - 2 pago prestamo

    class Meta:
        verbose_name = 'TransaccionPrestamo'
        verbose_name_plural = 'TransaccionPrestamo'
        ordering = ['-transaccion__fecha']

    def __str__(self):
        return "{} - Prestamo {} - Transaccion {} - $ {}".format(self.id, self.prestamo.id, self.transaccion.id, self.transaccion.cantidad)

class CreditCard(models.Model):
    nombre = models.CharField(max_length=90)
    cupo = models.IntegerField()
    cupoDisponible = models.IntegerField('Cupo disponible')
    diaCorte = models.IntegerField('Dia de corte')
    diaPago = models.IntegerField('Dia de pago')
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    visible = models.BooleanField('Visible', default=True)

    class Meta:
        verbose_name = 'CreditCard'
        verbose_name_plural = 'CreditCards'
        ordering = ['id']

    def __str__(self):
        return self.nombre

    def deuda(self):
        return self.cupo - self.cupoDisponible

class CompraCredito(models.Model):
    creditCard = models.ForeignKey(CreditCard, null=False, blank=False, on_delete=models.CASCADE)
    etiqueta = models.ForeignKey(Etiqueta, null=True, blank=True, on_delete=models.CASCADE)
    valor = models.IntegerField('Valor de la compra')
    cuotas = models.IntegerField('Número de cuotas', default=1)
    info = models.TextField('Informacion', max_length=300)
    deuda = models.IntegerField()
    cancelada = models.BooleanField('Cancelada', default=False)
    fecha = models.DateTimeField('Fecha')

    class Meta:
        verbose_name = 'CompraCredito'
        verbose_name_plural = 'CompraCredito'
        ordering = ['-fecha']

    def __str__(self):
        return "{} {} {}".format(self.creditCard.nombre, self.valor, self.fecha)

class TransaccionPagoCredito(models.Model):
    compraCredito = models.ForeignKey(CompraCredito, null=False, blank=False, on_delete=models.CASCADE)
    transaccion = models.ForeignKey(Transaccion, null=False, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'TransaccionPagoCredito'
        verbose_name_plural = 'TransaccionPagoCredito'
        ordering = ['id']

    def __str__(self):
        return "{} - {} | ({})Transaccion".format(self.compraCredito.id, self.compraCredito.creditCard.nombre, self.transaccion.id)

class GrupoTransaccion(models.Model):
    transaccionPadre = models.ForeignKey(Transaccion, null=False, blank=False, on_delete=models.CASCADE, related_name='transacciones_padres')
    transaccionHija = models.ForeignKey(Transaccion, null=False, blank=False, on_delete=models.CASCADE, related_name='transacciones_hijas')
    class Meta:
        verbose_name = 'GrupoTransaccion'
        verbose_name_plural = 'GrupoTransaccion'
    def __str__(self):
        return "{} - {}".format(self.transaccionPadre, self.transaccionHija)

class CompraCreditoPrestamo(models.Model):
    compraCredito = models.ForeignKey(CompraCredito, null=False, blank=False, on_delete=models.CASCADE)
    prestamo = models.ForeignKey(Prestamo, null=False, blank=False, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'CompraCreditoPrestamo'
        verbose_name_plural = 'CompraCreditoPrestamo'

class SolicitudPagoPrestamo(models.Model):
    pagoMultiple = models.BooleanField(default=False)
    valor = models.IntegerField(default=0)
    info = models.CharField(max_length=250, null=False, blank=False, default="")
    prestamo = models.ForeignKey(Prestamo, null=True, blank=True, on_delete=models.CASCADE)
    cuenta = models.ForeignKey(Cuenta, null=True, blank=True, on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    fechaPago = models.CharField(max_length=250, null=True, blank=True)
    pagoMultipleTipoPrestamo = models.CharField(max_length=20, null=True, blank=True)
    usuarioSolicita = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_solicita')
    usuarioAprueba = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='user_aprueba')
    fechaSolicitud = models.DateTimeField()
    estado = models.IntegerField(default=0) # 0-Creado, 1-Aprobada, 2-Rechazada
    class Meta:
        ordering = ['-fechaSolicitud']
    def __str__(self):
        return "{} - {} - Estado {}".format(self.id, self.usuarioSolicita, self.estado)

class SolicitudCreacionPrestamo(models.Model):
    tipo = models.CharField(max_length=30)
    valor = models.IntegerField()
    info = models.TextField()
    fechaPrestamo = models.CharField(max_length=100, null=True, blank=True)
    cuenta = models.ForeignKey(Cuenta, null=True, blank=True, on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, null=False, blank=False, on_delete=models.CASCADE)
    usuarioSolicita = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userSolicita')
    usuarioAprueba = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='userAprueba')
    fechaSolicitud = models.DateTimeField()
    estado = models.IntegerField(default=0) # 0-Creado, 1-Aprobada, 2-Rechazada
    class Meta:
        ordering = ['-fechaSolicitud']
    def __str__(self):
        return "{} - {} - Estado {}".format(self.id, self.usuarioSolicita, self.estado)

templates/contabilidad/etiqueta/crear_etiqueta.html
{% extends 'base/base.html' %}

{% block title %}Formulario de Etiqueta{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 offset-md-3 col-md-6">
                <div class="card animate__animated animate__fadeIn">
                    <div class="card-header text-center">
                        Formulario de Etiqueta
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <center>
                                <button type="submit" class="btn btn-primary btn-flat">Guardar</button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/contabilidad/etiqueta/etiqueta_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %}Eliminar Etiqueta{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 offset-md-3 col-md-6">
                <div class="card animate__animated animate__zoomIn">
                    <div class="card-header text-center">
                        Eliminar Etiqueta
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                             <p>
                                 ¿Desea eliminar el registro {{ object }}?
                             </p>
                            <center>
                                <a href="{% url 'panel:listar_etiquetas' %}" class="btn btn-outline-dark">Cancelar</a>
                                <button type="submit" class="btn btn-danger">Si Eliminar</button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/contabilidad/etiqueta/listar_etiquetas.html
{% extends 'base/base.html' %}

{% block title %}Mis Etiquetas{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="offset-lg-1 col-lg-6">
                <div class="m-b-20 text-center text-light animate__animated animate__fadeInDown">
                    <b class="fs-18">Etiquetas</b>
                    <a href="{% url 'panel:crear_etiqueta' %}" class="btn btn-sm btn-outline-light">
                        Crear  <i class="fal fa-plus"></i></a>
                </div>
                <div class="card animate__animated animate__fadeIn">
                    <div class="card-body">
                        {% if etiquetas %}
                        <table class="table table-sm table-responsive-sm">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Registros</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for e in etiquetas %}
                                    <tr>
                                        <td><a href="{% url 'panel:movimientos_etiqueta' e.id %}">{{e.nombre}}</a></td>
                                        <td class="text-center">{{e.transaccion_set.count}}</td>
                                        <td>
                                            <a href="{% url 'panel:editar_etiqueta' e.id %}" class="btn btn-sm btn-outline-success">
                                            <i class="fal fa-edit"></i></a>
                                        </td>
                                        <td>
                                            {% if e.transaccion_set.count == 0 %}
                                                <a href="{% url 'panel:eliminar_etiqueta' e.id %}" class="btn btn-sm btn-outline-danger">
                                                    <i class="fal fa-trash-alt"></i>
                                                </a>
                                            {% else %}
                                                <a href="#" class="btn btn-sm btn-outline-secondary disabled">
                                                    <i class="fal fa-trash-alt"></i>
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <div class="fs-18 text-center text-secondary">
                                <i class="fal fa-transporter-empty fa-4x"></i> <br><br>
                                No se han registrado etiquetas
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="offset-lg-2 col-lg-3 pt-3">
                {% include 'base/panel_enlaces.html' %}
                <br>
                {% include 'base/panel_reportes.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/contabilidad/etiqueta/movimientos_etiqueta.html
{% extends 'base/base.html' %}
{% load static %}
{% load misTags %}

{% block title %}Movimientos por {{etiqueta.nombre}}{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card animate__animated animate__fadeIn">
                    <div class="card-header text-center">
                        Movimientos etiqueta: {{etiqueta.nombre}}
                    </div>
                    <div class="card-body">
                        {% if transacciones %}
                            <p>
                                <a href="{% url 'reporte:reporte_subtag_mensual' etiqueta.id periodoActual %}" class="btn btn-outline-primary float-right">Reporte sub tags</a>
                                <b>Total ingresos:</b> ${{totalIngresos|puntomil}} <br>
                                <b>Total egresos:</b> ${{totalEgresos|puntomil}}
                            </p>
                            <table class="table table-responsive-sm" id="datatable">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Cuenta</th>
                                        <th>Valor</th>
                                        <th>Sub tag</th>
                                        <th>Info</th>
                                        <th>Ver</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for t in transacciones %}
                                        <tr class="{{t|textcolor}}">
                                            <td>
                                                <span class="d-none d-md-block">
                                                    {{t.fecha|date:'D, d/m/y h:iA'}}
                                                </span>
                                                <span  class="d-md-none">
                                                    {{t.fecha|date:'d/m/y h:iA'}}
                                                </span>
                                            </td>
                                            <td>{{t.cuenta.nombre}}</td>
                                            <td> {{t.tipo|signo}}${{t.cantidad|puntomil}}</td>
                                            <td>{{t.subtag.nombre}}</td>
                                            <td>{{t.info|truncatechars:'30'}}</td>
                                            <td>
                                                <a href="{% url 'panel:vista_transaccion' t.id %}"
                                                    class="btn btn-sm btn-outline-primary">
                                                <i class="fas fa-external-link-alt"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="fs-18 text-center">
                                No hay movimientos en esta etiqueta
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-lg-3 pt-3">
                {% include 'user/alert_switchUserSetting.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/contabilidad/etiqueta/movimientos_etiqueta_mes.html
{% extends 'base/base.html' %}
{% load static %}
{% load misTags %}

{% block title %} {{tipo}} perido {{periodo}} {% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h4 class="text-light text-center mb-3 animate__animated animate__fadeInDown">{{tipo}} {{etiqueta}} periodo {{periodo}}</h4>
                <div class="card animate__animated animate__fadeIn">
                    <div class="card-body">
                        {% if transacciones %}
                            <table class="table table-responsive-sm" id="datatable">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Cuenta</th>
                                        <th>Valor</th>
                                        <th>Info</th>
                                        <th>Ver</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for t in transacciones %}
                                        <tr class="{{t|textcolor}}">
                                            <td>
                                                <span class="d-none d-md-block">
                                                    {{t.fecha|date:'D, d/m/y h:iA'}}
                                                </span>
                                                <span  class="d-md-none">
                                                    {{t.fecha|date:'d/m/y h:iA'}}
                                                </span>
                                            </td>
                                            <td>{{t.cuenta.nombre}}</td>
                                            <td> {{t.tipo|signo}}${{t.cantidad|puntomil}}</td>
                                            <td>{{t.info|truncatechars:'40'}}</td>
                                            <td>
                                                <a href="{% url 'panel:vista_transaccion' t.id %}"
                                                    class="btn btn-sm btn-outline-primary">
                                                <i class="fal fa-external-link-alt"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="fs-18 text-center">
                                No hay movimientos en esta etiqueta
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}