apps/apto/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('crearRecibo/', crearRecibo, name='crearRecibo'),
    path('recibo/<int:id>/', vistaRecibo, name='vistaRecibo'),
    path('recibosPeriodo/<int:periodoId>/', recibosPeriodo, name='recibosPeriodo'),
    path('addReciboInternet/<int:periodoId>/', addReciboInternet, name='addReciboInternet'),
    path('crearPrestamoRecibosPeriodo/<int:periodoId>/<int:userId>/', crearPrestamoRecibosPeriodo, name='crearPrestamoRecibosPeriodo'),
]

miscuentas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.contabilidad.urls', 'panel'))),
    path('user/', include(('apps.usuario.urls', 'user'))),
    path('reporte/', include(('apps.reporte.urls', 'reporte'))),
    path('pagos/', include(('apps.pagos.urls', 'pagos'))),
    path('shared/', include(('apps.publico.urls', 'publico'))),
    path('apto/', include(('apps.apto.urls', 'apto'))),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/apto/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.contabilidad.models import Prestamo, Persona

class Apartamento(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return "{}".format(self.nombre)

class Pagador(models.Model):
    apto = models.ForeignKey(Apartamento, null=False, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.user.username)

class PersonaPagador(models.Model):
    nombre = models.CharField(max_length=50)
    pagador = models.ForeignKey(Pagador, null=False, blank=False, on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.nombre)

class Estadia(models.Model):
    fechaInicio = models.CharField(max_length=100)
    fechaFin = models.CharField(max_length=100)
    persona = models.ForeignKey(PersonaPagador, null=False, blank=False, on_delete=models.CASCADE)
    def __str__(self):
        return "{} - {} | {}".format(self.fechaInicio, self.fechaFin, self.persona.nombre)

class Empresa(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return "{}".format(self.nombre)

class Periodo(models.Model):
    nombre = models.CharField(max_length=20)
    class Meta:
        ordering = ['-nombre']
    def __str__(self):
        return "{}".format(self.nombre)

class Recibo(models.Model):
    valorPago = models.IntegerField()
    fechaInicio = models.CharField(max_length=100)
    fechaFin = models.CharField(max_length=100)
    diasFacturados = models.IntegerField()
    periodo = models.ForeignKey(Periodo, null=False, blank=False, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
    apto = models.ForeignKey(Apartamento, null=False, blank=False, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-periodo__nombre']
    def __str__(self):
        return "{} [{}] ${}".format(self.empresa, self.periodo, self.valorPago)

class PagadorRecibo(models.Model):
    valorPago = models.IntegerField()
    pagador = models.ForeignKey(Pagador, null=False, blank=False, on_delete=models.CASCADE)
    recibo = models.ForeignKey(Recibo, null=False, blank=False, on_delete=models.CASCADE)
    def __str__(self):
        return "{} ({} {}) -> ${}".format(self.pagador.user.username, self.recibo.empresa.nombre, self.recibo.periodo, self.valorPago )

class PeriodoPrestamoPersona(models.Model):
    periodo = models.ForeignKey(Periodo, null=False, blank=False, on_delete=models.CASCADE)
    prestamo = models.ForeignKey(Prestamo, null=False, blank=False, on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, null=False, blank=False, on_delete=models.CASCADE)

apps/apto/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.db import transaction
from apps.contabilidad.myFuncs import *
from apps.usuario.userSettingFuncs import getUserSetting
from apps.usuario.models import UserPersona
from .myFuncs import *
from .models import *

@login_required
def home(request):
    pagador = Pagador.objects.filter(user=request.user).first()
    context = {
        'recibos': Recibo.objects.filter(apto=pagador.apto).all(),
        'periodos': Periodo.objects.all() 
    }
    return render(request, 'apto/home.html', context)

@login_required
def recibosPeriodo(request, periodoId):
    periodo = get_object_or_404(Periodo, id=periodoId)
    pagador = Pagador.objects.filter(user=request.user).first()
    tableData = GetTableDataRecibosPeriodo(periodo, pagador.apto)
    context = {
        'periodo': periodo,
        'pagadores': tableData['pagadores'],
        'tableData': tableData['tableData']
    }
    return render(request, 'apto/recibosPeriodo.html', context)

@login_required
def crearRecibo(request):
    if request.method == 'POST':
        try:
            recibo = Recibo(
                valorPago = int(request.POST.get('valorPago').replace('.','')),
                fechaInicio = request.POST.get('fechaInicio'),
                fechaFin = request.POST.get('fechaFin'),
                diasFacturados = CalcularNumeroDias(request.POST.get('fechaInicio'), request.POST.get('fechaFin')),
                periodo = GetPeriodo(request.POST.get('periodo')),
                empresa = Empresa.objects.filter(id=int(request.POST.get('empresa'))).first(),
                apto = GetAptoFromRequest(request)
            )
            recibo.save()
            alert(request, 'Se registro el recibo correctamente')
        except Exception as ex:
            printException(ex)
            alert(request, 'No fue posible crear el recibo', 'e')
        return redirect('apto:home')

    context = {
        'empresas' : Empresa.objects.all()
    }
    return render(request, 'apto/crearRecibo.html', context)

@login_required
def vistaRecibo(request, id):
    recibo = get_object_or_404(Recibo, id=id)
    context = {
        'recibo': recibo
    }
    if recibo.empresa != GetEmpresaInternet():
        context['reciboValorPagoFijo'] = False
        datosEstadiasPersonas = ObtenerDatosEstadiasPersonas(recibo)
        estadiaData = ObtenerDatosTablaEstadiaPersona(recibo, datosEstadiasPersonas)
        context['listaDias'] = estadiaData['listaDias']
        context['estadiaPersonas'] = estadiaData['estadiaPersonas']

        dataPago = CalcularPagoRecibo(recibo, datosEstadiasPersonas)
        context['listaPagadorRecibo'] = dataPago['listaPagadorRecibo']
        context['tableData'] = dataPago['tableData']
        context['sumaPagosPagadores'] = dataPago['sumaPagosPagadores']
    else:
        context['reciboValorPagoFijo'] = True
        pagadoresRecibos = PagadorRecibo.objects.filter(recibo=recibo).all()
        if not pagadoresRecibos:
            print('no existen calculo apgadores refirecionadno')
            return redirect('apto:addReciboInternet', recibo.periodo.id)
        context['listaPagadorRecibo'] = pagadoresRecibos

    return render(request, 'apto/vistaRecibo.html', context)

@login_required
def addReciboInternet(request, periodoId):
    periodo = get_object_or_404(Periodo, id=periodoId)
    valorRecibo = getUserSetting('ValorReciboInternet', request.user)
    if valorRecibo:
        seCreoPagadorReciboNuevo = False
        try:
            with transaction.atomic():
                pagadores = GetPagadores(request)
                recibo = GetReciboInternetByPeriodo(request, periodo, valorRecibo)
                for pagador in pagadores:
                    pagadorReciboExiste = PagadorRecibo.objects.filter(pagador=pagador, recibo=recibo).first()
                    if not pagadorReciboExiste:
                        pagadorRecibo = PagadorRecibo(
                            valorPago=round(valorRecibo/len(pagadores)),
                            pagador=pagador,
                            recibo=recibo
                        )
                        pagadorRecibo.save()
                        seCreoPagadorReciboNuevo = True
                if seCreoPagadorReciboNuevo:
                    alert(request, 'El recibo del internet se agregó correctamente')
                else:
                    alert(request, 'La información de pago del recibo de internet anteriormente', 'i')
        except Exception as ex:
            printException(ex)
            alert(request, 'Ocurrio un error al calcular la información de pago del recibo de internet', 'e')
        
    else:
        alert(request, 'No se ha establecido el valor del recibo', 'e')
    # return redirect('apto:recibosPeriodo', periodo.id)
    return RedireccionarVistaAnterior(request)

@login_required
def crearPrestamoRecibosPeriodo(request, periodoId, userId):
    periodo = get_object_or_404(Periodo, id=periodoId)
    user = get_object_or_404(User, id=userId)
    userPersona = UserPersona.objects.filter(admin=request.user, user=user).first()
    if userPersona:
        periodoPrestamoPersona = PeriodoPrestamoPersona.objects.filter(periodo=periodo, persona=userPersona.persona).first()
        if not periodoPrestamoPersona:
            try:
                with transaction.atomic():
                    infoPago = GetInfoPagosRecibosPeriodoUser(request, periodo, user)
                    prestamo = crearPrestamo(request, 'yopresto', infoPago['valorTotalPago'], infoPago['mensaje'], None, userPersona.persona)
                    periodoPrestamoPersona = PeriodoPrestamoPersona(
                        periodo=periodo,
                        prestamo=prestamo,
                        persona=userPersona.persona
                    )
                    periodoPrestamoPersona.save()
                    alert(request, 'Se ha creado el prestamo con '+user.username)
            except Exception as ex:
                printException(ex)
                alert(request, 'Ocurrio un error el intentar crear el prestamo', 'e')
        else:
            return redirect('panel:vista_prestamo', periodoPrestamoPersona.prestamo.id)
    else:
        alert(request, 'No se encontro una persona relacionada a este usuario', 'e')
    
    return RedireccionarVistaAnterior(request)

templates/apto/crearRecibo.html
{% extends 'base/base.html' %}
{% load misTags %}

{% block title %}Agregar Recibo{% endblock %}

{% block contenido %}
    <div class="container pt-4">
        <div class="row">
            <div class="col-sm-12 offset-md-3 col-md-6">
                <div class="card animate__animated animate__fadeInUp">
                    <div class="card-header text-center">
                        Agregar Recibo
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="empresa">Servicio</label>
                                <select class="form-control" name="empresa" id="empresa" required>
                                    {% for item in empresas %}
                                        <option value="{{item.id}}">{{item.nombre}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="pb-2">
                                <label for="periodo">Periodo</label>
                                <input type="text" class="form-control fechaPeriodo" name="periodo" id="periodo" required>
                            </div>
                            <div class="pb-3">
                                <label for="valorPago">Valor del total</label>
                                <input type="text" id="valorPago" name="valorPago" class="form-control" autocomplete="off" placeholder="$" required >
                            </div>
                            <div class="pb-2">
                                <label for="fechaInicio">Fecha Inicio</label>
                                <input type="text" class="form-control fechaIF" name="fechaInicio" id="fechaInicio" required>
                            </div>
                            <div class="pb-2">
                                <label for="fechaFin">Fecha Fin</label>
                                <input type="text" class="form-control fechaIF" name="fechaFin" id="fechaFin" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary btn-flat">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.5.4"></script>
    <script type="text/javascript">
        new AutoNumeric('#valorPago', {
            allowDecimalPadding: false,
            digitGroupSeparator: ".",
            decimalCharacter: ",",
            currencySymbol : ''
        });
    </script>
{% endblock %}

templates/apto/home.html
{% extends 'base/base.html' %}
{% load misTags %}

{% block title %}Apto{% endblock %}

{% block contenido %}

    <div class="container pt-2">
        <div class="row">
            <div class="col-lg-8 mb-4">
                <div class="mb-3 text-center text-light animate__animated animate__fadeInDown">
                    <b class="fs-22">Recibos</b>
                    <a href="{% url 'apto:crearRecibo' %}" class="btn btn-sm btn-outline-light">
                        Agregar  <i class="fal fa-plus"></i></a>
                </div>
                <div class="card">
                    <div class="card-body">
                        {% if recibos %}
                            <table class="table table-responsive-sm" id="datatable">
                                <thead>
                                    <tr>
                                        <th>Servicio</th>
                                        <th>Periodo</th>
                                        <th>Valor Pago</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in recibos %}
                                        <tr>
                                            <td>{{item.empresa.nombre}}</td>
                                            <td>{{item.periodo}}</td>
                                            <td>{{item.valorPago|dinero}}</td>
                                            <td>
                                                <a href="{% url 'apto:vistaRecibo' item.id %}" class="btn btn-sm btn-outline-primary">Consultar</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <h4 class="text-center text-secondary py-4">
                                <i class="fal fa-smile-wink"></i> Todavia no se registran recibos
                            </h4>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mb-3 text-center text-light animate__animated animate__fadeInDown">
                    <b class="fs-22">Periodos</b>
                </div>
                <div class="list-group">
                    {% for periodo in periodos %}
                        <a href="{% url 'apto:recibosPeriodo' periodo.id %}" class="list-group-item list-group-item-action">
                            Recibos periodo {{periodo}} <span class="badge badge-primary">{{periodo.recibo_set.count}}</span>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/apto/recibosPeriodo.html
{% extends 'base/base.html' %}
{% load misTags %}

{% block title %}Recibos periodo {{periodo.nombre}}{% endblock %}

{% block contenido %}

    <div class="container pt-2">
        <div class="row">
            <div class="col-lg-9 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="text-center">Recibos periodo {{periodo.nombre}}</h4>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="table-primary">
                                    <th>Servicio</th>
                                    {% for pagador in pagadores %}
                                        <th>{{pagador.user.username|capfirst}}</th>
                                    {% endfor %}
                                    {% if request.user.is_superuser %}
                                    <th>Sumatoria</th>
                                    {% endif %}
                                    <th>Valor Recibo</th>
                                </thead>
                                <tbody>
                                    {% for row in tableData %}
                                        <tr {% if row.0 == 'Total' %} class="table-primary"  {% endif %}>
                                            {% for item in row %}
                                                {% if forloop.counter0 == 0 %}
                                                    <td>{{item}}</td>
                                                {% elif forloop.counter0 == row|length|add:"-2" and not request.user.is_superuser %}
                                                    
                                                {% else %}
                                                    <td>{{item|dinero}}</td>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% if request.user.is_superuser %}
                <div class="col-lg-3">
                    <div class="list-group">
                        <a href="{% url 'apto:addReciboInternet' periodo.id %}" class="list-group-item list-group-item-action">Agregar Recibo Internet</a>
                        {% for pagador in pagadores %}
                            {% if pagador.user != request.user %}
                                <a href="{% url 'apto:crearPrestamoRecibosPeriodo' periodo.id pagador.user.id %}" class="list-group-item list-group-item-action">Crear prestamo para {{pagador.user.username|capfirst}}</a>
                            {% endif %}
                        {% endfor %}
                        
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    
{% endblock %}

templates/apto/vistaRecibo.html
{% extends 'base/base.html' %}
{% load misTags %}

{% block title %}Vista Recibo{% endblock %}

{% block contenido %}
    <div class="container pt-4">
        <div class="row">
            <div class="col-lg-4 pb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center">Recibo de {{recibo.empresa.nombre}}</h5>
                        <table class="table table-sm table-borderless mb-0">
                            <tbody>
                                <tr>
                                    <th>Periodo:</th>
                                    <td>{{recibo.periodo}}</td>
                                </tr>
                                <tr>
                                    <th>Valor:</th>
                                    <td>{{recibo.valorPago|dinero}}</td>
                                </tr>
                                <tr>
                                    <th>Inicio facturación:</th>
                                    <td>{{recibo.fechaInicio}}</td>
                                </tr>
                                <tr>
                                    <th>Final facturación:</th>
                                    <td>{{recibo.fechaFin}}</td>
                                </tr>
                                <tr>
                                    <th>Dias facturados:</th>
                                    <td>{{recibo.diasFacturados}} dias</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 pb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center">Información de pago por persona</h5>
                        {% if not reciboValorPagoFijo and sumaPagosPagadores != recibo.valorPago %}
                            <div class="alert alert-danger" role="alert">
                                <b>Error:</b> El cálculo no es válido debido a que la suma de los pagos por persona no es igual al valor del recibo.
                                La sumatoria de los pagos es igual a {{sumaPagosPagadores|dinero}}.
                            </div>
                        {% endif %}
                        <div class="table-responsive">
                            <table class="table table-sm table-bordered table-striped mb-0">
                                <thead>
                                    <th>Persona</th>
                                    <th>Valor a pagar</th>
                                </thead>
                                <tbody>
                                    {% for pagadorRecibo in listaPagadorRecibo %}
                                        <tr>   
                                            <td>{{pagadorRecibo.pagador.user|capfirst}}</td>                                 
                                            <td>{{pagadorRecibo.valorPago|DineroSinDecimales}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% if not reciboValorPagoFijo %}
            <div class="col-12 pb-4">
                <div class="card">
                    <div class="card-body pb-1">
                        <h5 class="text-center">Estadias por persona</h5>
                        <div class="table-responsive">
                            <table class="table table-sm table-bordered">
                                <thead>
                                    <th>Persona</th>
                                    {% for dia in listaDias %}
                                        <th>{{dia}}</th>
                                    {% endfor %}
                                </thead>
                                <tbody>
                                    {% for key, value in estadiaPersonas.items %}
                                        <tr>
                                            <th>{{key}}</th>
                                            {% for i in value %}
                                                <td class="{% if i == 1 %}table-primary{% endif %}"></td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-bordered table-striped">
                                <thead>
                                    <th>Dia</th>
                                    {% for pagadorRecibo in listaPagadorRecibo %}
                                        <th>{{pagadorRecibo.pagador.user|capfirst}}</th>
                                    {% endfor %}
                                </thead>
                                <tbody>
                                    {% for row in tableData %}
                                        <tr>
                                            {% for col in row %}
                                                <td>
                                                    {% if forloop.counter0 == 0 %}
                                                        {{col}}
                                                    {% else %}
                                                        {{col.nPersonas}} <i class="fad fa-users"></i> - ${{col.valorPagoDia|ReducirDecimales:2}}
                                                    {% endif %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}